"""Cross-check dashboard/x402-client.js against the OKX Payment SDK.

The browser signs the EIP-3009 authorization, but the OKX facilitator is what
verifies it, so the JS must produce byte-identical typed data and an envelope
the SDK's own decoder accepts. Both are asserted here by driving the browser
module under Node against a 402 produced by the SDK itself.
"""

import json
import shutil
import subprocess
from pathlib import Path

import pytest

pytest.importorskip("x402", reason="okxweb3-app-x402 not installed")
pytestmark = pytest.mark.skipif(shutil.which("node") is None, reason="node not installed")

from fastapi.testclient import TestClient  # noqa: E402

from tests.test_okx_payments import WALLET, _app_with_middleware  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
CLIENT_JS = REPO / "dashboard" / "x402-client.js"

PAYER = "0x1111111111111111111111111111111111111111"
NOW = 1769000000
NONCE = "0x" + "ab" * 32
VALIDITY_BUFFER = 600

# Drives the browser module under Node with a fixed nonce and clock so the
# Python side can rebuild the identical authorization.
DRIVER_JS = """
const {{ readFileSync }} = require('node:fs');
globalThis.btoa = (s) => Buffer.from(s, 'binary').toString('base64');
globalThis.atob = (s) => Buffer.from(s, 'base64').toString('binary');
new Function(readFileSync({client!r}, 'utf8'))();

const requirements = X402Client.decodeRequirements({header!r});
const accept = requirements.accepts[0];
const authorization = X402Client.buildAuthorization(accept, {payer!r}, {now});
authorization.nonce = {nonce!r};
console.log(JSON.stringify({{
  typedData: X402Client.buildTypedData(accept, authorization),
  header: X402Client.buildPaymentHeader(
    requirements, accept, authorization, '0x' + '11'.repeat(65)
  ),
}}));
"""


@pytest.fixture
def requirements_header(monkeypatch):
    """A live PAYMENT-REQUIRED header, generated by the SDK middleware."""
    monkeypatch.setenv("ASP_WALLET", WALLET)
    monkeypatch.setenv("PAYMENT_CHAIN", "eip155:196")
    monkeypatch.setenv("INVOICE_PRICE_USDT", "0.50")
    app, installed = _app_with_middleware()
    assert installed
    response = TestClient(app).post("/api/v1/invoice", json={})
    assert response.status_code == 402
    return response.headers["payment-required"]


@pytest.fixture
def js_output(requirements_header, tmp_path):
    script = tmp_path / "driver.js"
    script.write_text(
        DRIVER_JS.format(
            client=str(CLIENT_JS), header=requirements_header,
            payer=PAYER, now=NOW, nonce=NONCE,
        )
    )
    result = subprocess.run(
        ["node", str(script)], capture_output=True, text=True, check=True
    )
    return json.loads(result.stdout)


def _sdk_typed_data(requirements_header):
    from x402.http.utils import safe_base64_decode
    from x402.mechanisms.evm.eip712 import build_typed_data_for_signing
    from x402.mechanisms.evm.types import ExactEIP3009Authorization

    accept = json.loads(safe_base64_decode(requirements_header))["accepts"][0]
    authorization = ExactEIP3009Authorization(
        from_address=PAYER,
        to=accept["payTo"],
        value=accept["amount"],
        valid_after=str(NOW - VALIDITY_BUFFER),
        valid_before=str(NOW + accept["maxTimeoutSeconds"]),
        nonce=NONCE,
    )
    return accept, build_typed_data_for_signing(
        authorization,
        int(accept["network"].split(":")[1]),
        accept["asset"],
        accept["extra"]["name"],
        accept["extra"]["version"],
    )


def test_typed_data_matches_the_sdk(requirements_header, js_output):
    accept, (domain, types, primary_type, message) = _sdk_typed_data(requirements_header)
    typed = js_output["typedData"]

    assert typed["domain"] == {
        "name": accept["extra"]["name"],
        "version": accept["extra"]["version"],
        "chainId": int(accept["network"].split(":")[1]),
        "verifyingContract": accept["asset"],
    }
    assert typed["domain"] == {
        "name": domain.name,
        "version": domain.version,
        "chainId": domain.chain_id,
        "verifyingContract": domain.verifying_contract,
    }
    assert typed["primaryType"] == primary_type
    # The SDK's own types dict carries no EIP712Domain entry; the wallet needs it.
    assert {k: v for k, v in typed["types"].items() if k != "EIP712Domain"} == types
    assert "EIP712Domain" in typed["types"]
    assert typed["message"] == {
        "from": message["from"],
        "to": message["to"],
        "value": str(message["value"]),
        "validAfter": str(message["validAfter"]),
        "validBefore": str(message["validBefore"]),
        "nonce": "0x" + message["nonce"].hex(),
    }


def test_payment_header_decodes_as_a_valid_payload(requirements_header, js_output):
    from x402.http.utils import decode_payment_signature_header, safe_base64_decode

    accept = json.loads(safe_base64_decode(requirements_header))["accepts"][0]
    payload = decode_payment_signature_header(js_output["header"])

    assert payload.x402_version == 2
    assert payload.get_scheme() == "exact"
    assert payload.get_network() == accept["network"]
    assert payload.accepted.pay_to == accept["payTo"]
    assert payload.accepted.amount == accept["amount"]
    assert payload.payload["authorization"]["nonce"] == NONCE
    assert payload.payload["authorization"]["from"] == PAYER
    assert payload.payload["signature"].startswith("0x")
